### ISSUE TITLE
ReadCSV should take a Reader as input rather than a string

### ISSUE THREAD

**Issue by tobgu** [kniren/gota#17]
I've started looking at reimplementing some of the functionality of https://github.com/tobgu/qcache in Go (currently python and pandas) and found gota. Looks good, keep it up!

I think it would be better to take a Reader as input to ReadCSV than a string. As it is right now I have to read all bytes from a reader into a byte buffer that then has to be converted to a string. That string is then immediately converted into a Reader in ReadCSV.

Do you agree?

**Comment by kniren** [comment]
Hi @tobgu this makes complete sense. Reading from a `Reader` should be the preferred way of dealing with this.

In addition to this, it would also make sense that the Save methods would write to a `Writer` or `WriteCloser` for consistency and better composability.

The exception to this would be the ReadRecords/SaveRecords methods, but for other formats (CSV, JSON, XML...) it should work.

**Comment by tobgu** [comment]
Sounds good!

**Comment by kniren** [comment]
I've finished with these modifications on the `dev` branch as of commit 48ef419800e1b5b6da58ebb2e2a6390224301de6

As a summary:

- `ReadCSV` now accepts an `io.Reader` instead of a `string`
- `SaveCSV`/`SaveJSON` now write directly to the given `io.Writer` instead of returning a `[]byte`
- `SaveRecords`/`SaveMaps` has been renamed to `Records`/`Maps` respectively to be consistent with the `Dense` method
- `ReadCSV`/`ReadMaps` has been renamed to `LoadCSV`/`LoadMaps` since they don't accept readers.
- `SaveCSV`/`SaveMaps` has been renamed to `WriteCSV`/`WriteMaps` for consistency with the `Read*` methods.
- `SaveMaps` was not working properly and thus it has been fixed.
